#!/bin/bash

WSYNC_DEBUG=${WSYNC_DEBUG:-0}

EVENTS=MODIFY,MOVED_TO,MOVED_FROM,CREATE

ARGS=$@
if [ $# -lt 1 ]; then
  echo 'wsync: inotifywait + rsync' >&2
  echo 'Keeps watching the source directory(ies) by inotifywait and when a modification is detected runs rsync with the specified arguments.' >&2
  echo '' >&2
  echo 'Usage:' >&2
  echo '    wsync [OPTION...] SRC... [DEST]' >&2
  echo '' >&2
  echo 'Any arguments are directly delegated to rsync.' >&2
  exit -1
fi

# Parse arguments and extract SRC
DIRS=()
for ARG in $ARGS; do
  if [[ ! $ARG == -* ]]; then
    DIRS+=($ARG)
  fi
done
SRCS=${DIRS[@]::${#DIRS[@]}-1}
DEST=${DIRS[-1]}


function printlog() {
  COLOR='\033[1;32m'    # Light green
  NC='\033[0m'
  D=`date +"%Y-%m-%d %H:%M:%S"`
  echo -e "${COLOR}$D wsync:${NC} $@"
}

printlog "Watch ${SRCS[@]} and sync to $DEST"

# Debug mode
QUIET_OPTION="-q"
if [ $WSYNC_DEBUG -ne 0 ]; then
  printlog "Debug mode"
  QUIET_OPTION=""
fi

# First run
printlog "Initial \"rsync ${ARGS}\""
BEFORE=$SECONDS
rsync ${ARGS}
ELAPSED=$(($SECONDS - $BEFORE))
printlog "Completed in ${ELAPSED}s"

# Watch & sync loop
inotifywait $QUIET_OPTION -rm -e $EVENTS ${SRCS[@]} | 
  while read events; do
    printlog "Modification detected. Running \"rsync ${ARGS}\""
    BEFORE=$SECONDS
    rsync ${ARGS}
    ELAPSED=$(($SECONDS - $BEFORE))
    printlog "Completed in ${ELAPSED}s"
    sleep 1
  done
