#!/bin/bash

EVENTS=MODIFY,CLOSE_WRITE,MOVED_TO,MOVED_FROM,MOVE,CREATE

ARGS=$@
if [ $# -lt 1 ]; then
  echo 'wsync: inotifywait + rsync' >&2
  echo 'Keeps watching the source directory(ies) by inotifywait and when a modification is detected runs rsync with the specified arguments.' >&2
  echo '' >&2
  echo 'Usage:' >&2
  echo '    wsync [OPTION...] SRC... [DEST]' >&2
  echo '' >&2
  echo 'Any arguments are directly delegated to rsync.' >&2
  exit -1
fi

DIRS=()
for ARG in $ARGS; do
  if [[ ! $ARG == -* ]]; then
    DIRS+=($ARG)
  fi
done

SRCS=${DIRS[@]::${#DIRS[@]}-1}

inotifywait -qrm -e $EVENTS ${SRCS[@]} | 
  while read events; do
    echo wsync: Modification detected. Running "rsync ${ARGS}"
    rsync ${ARGS}
    echo "wsync: Completed"
    sleep 0.02
  done
